#' Dimension estimation 1
#'
#' Estimate pixel dimensions from an _extern.inf file
#' @param filename Path to the desired .raw folder 
#' @return The x,y dimension lengths
#' @examples 
#' xydims <- estDims("C:/some_tq_data.raw");
#' @export
estDims <- function(filename = NULL){
  
  # if folder is provided, set filename to _extern.inf within that folder
  if(fs::is_dir(filename) == TRUE){
    
    # add trailing slash if not there
    
    if(substr(filename, nchar(filename), nchar(filename)) != "/"){
      filename <- paste0(filename, "/")
    }
    
    filename <- paste0(filename, "_extern.inf")
  }
  
  file_in <- readChar(filename, nchars = 10000000)
  xlen <- as.numeric(strsplit(strsplit(utf8::as_utf8(file_in), "DesiXLength\t\t")[[1]][2], "\r")[[1]][1])
  ylen <- as.numeric(strsplit(strsplit(utf8::as_utf8(file_in), "DesiYLength\t\t")[[1]][2], "\r")[[1]][1])
  xstep <- as.numeric(strsplit(strsplit(utf8::as_utf8(file_in), "DesiXStep\t\t")[[1]][2], "\r")[[1]][1])
  ystep <- as.numeric(strsplit(strsplit(utf8::as_utf8(file_in), "DesiYStep\t\t")[[1]][2], "\r")[[1]][1])
  
  dim1 <- round(xlen/xstep)
  dim2 <- round(ylen/ystep)
  
  if(xstep != ystep){
    warning("Pixel step values do not match, probably returning a wacky dimension")
  }
  return(c(dim1, dim2))
}

#' Dimension estimation 2
#'
#' Estimate pixel dimensions from from total scan number
#' @param n The total number of scans in a file 
#' @return A list of potential pixel dimensions for the given length
#' @examples 
#' dimslist <- estDims2(40000);
#' @export

estDims2 <- function(n) {
  # find all factors of input number
  factors <- function(num) {
    result <- c()
    for (i in 1:sqrt(num)) {
      if (num %% i == 0) {
        result <- c(result, i)
        if (i != num / i) {
          result <- c(result, num / i)
        }
      }
    }
    sort(result)
  }
  
  # Get all factors of n
  factor_list <- factors(n)
  
  # Find combinations of factors that multiply to n
  combinations <- list()
  for (i in seq_along(factor_list)) {
    for (j in i:length(factor_list)) {
      if (factor_list[i] * factor_list[j] == n) {
        combinations <- c(combinations, list(c(factor_list[i], factor_list[j])))
      }
    }
  }
  combinations <- combinations[-1]
  combinations <- c(combinations, lapply(combinations, rev))
  return(combinations)
}

#' Dimension estimation 3
#'
#' Get global coordinate positions reported from the instrument/stage
#' @param filename Path to the desired .raw folder 
#' @param exe Path to Waters-provided .exe file, defaults to TQ specific MRMProcessing.exe  
#' @return A data frame of x,y coordinate pairs for each scan 
#' @examples 
#' xypos <- getPos("C:/some_tq_data.raw")
#' xydims <- c(length(unique(xypos[,1], unique(xypos[,2]))))
#' @export
getPos <- function(filename = NULL, exe = "MRM"){
  if(exe == "MRM"){
    exe <- "C:/Program Files (x86)/Waters/DESI Method Editor/MRMProcessing.exe"
  }
  
  file1 <- normalizePath(filename)
  file2 <- tempfile(pattern = "file", tmpdir = tempdir(), fileext = ".txt")
  
  system2(command = exe, args = paste0("-i ", file1, " -o ", file2), stderr = "TRUE")
  
  temptsv <- read.csv(file2, sep = "\t", row.names = NULL)
  
  xpos <- temptsv[3:nrow(temptsv),2]
  ypos <- temptsv[3:nrow(temptsv),3]
  
  pos_df <- data.frame(xpos = xpos, ypos = ypos)
  return(pos_df)
}

#' Dimension pair plotting
#'
#' Plot every possible coordinate pair from an estDims2 generated list
#' @param dims_list A list of coordinate pairs generated by estDims2 
#' @param input_data A data matrix generated from data import functions  
#' @return A data frame of x,y coordinate pairs for each scan 
#' @examples 
#' plotlist <- plotDims(dimslist, datamatrix)
#' plotlist[[10]]
#' @export
plotDims <- function(dims_list, input_data){
  plotlist <- list()
  
  for(i in 1:length(dims_list)){
    cimgplot <- matrix(data = NA, nrow = dims_list[[i]][1], ncol = dims_list[[i]][2])
    
    # datamatrix[i,1] in the following code addresses a column of the datamatrix, ie
    # the first compound, replace with the compound number you wish to image
    
    cimgplot <- sapply(1:nrow(input_data), function(i) {
      sum(input_data[i,])})
    cimgplot <- imager::as.cimg(cimgplot, x = dims_list[[i]][1], y = dims_list[[i]][2])
    
    # for aesthetic reasons you may wish to reverse scales, in this case y is reversed for
    # ease of comparison with Yuchen's plots, you can add or remove the "rev()" call
    
    p <- ggplot(data = as.data.frame(cimgplot)) +
      geom_raster(aes(x = x, y = rev(y), fill = log(value))) +
      scale_fill_viridis_c(option = "magma", name = "Intensity (A.U)") + coord_fixed() + 
      scale_x_continuous(expand=c(0,0))+scale_y_continuous(expand=c(0,0), 
                                                           trans=scales::reverse_trans()) + xlab(NULL) + ylab(NULL) + 
      ggtitle(paste0(dims_list[[i]][1], "x", dims_list[[i]][2])) + theme(plot.title = element_text(hjust = 0.5))
    plotlist[[i]] <- p
  }
  return(plotlist)
}
